<?php
/**
 * Bloggy Child
 *
 * ROUNDHOUSE DESIGNS
 *
 * @package WordPress
 * @subpackage rhd
 **/

/* ==========================================================================
   Initialization
   ========================================================================== */

define( 'RHD_CHILD_DIR', get_stylesheet_directory_uri() );


// Enqueue Parent Theme
add_action( 'wp_enqueue_scripts', 'rhd_theme_enqueue_styles' );
function rhd_theme_enqueue_styles() {
    wp_enqueue_style( 'parent-style', RHD_THEME_DIR . '/style.css' );
    wp_enqueue_style( 'child-main', RHD_CHILD_DIR . '/css/main.css', array( 'rhd-main' ) );

    wp_register_style( 'google-fonts', '//fonts.googleapis.com/css?family=Oswald:400,700' );
}

add_action( 'wp_enqueue_scripts', 'rhd_theme_enqueue_scripts' );
function rhd_theme_enqueue_scripts() {
	wp_enqueue_script( 'child-main', RHD_CHILD_DIR . '/js/child-main.js', array( 'jquery', 'rhd-main' ), null, true );

    // Localize data for client-side use
	global $wp_query;
	$data = array(
		'home_url' => home_url(),
		'parent_dir' => RHD_THEME_DIR,
		'child_dir' => get_stylesheet_directory_uri(),
		'img_dir' => get_stylesheet_directory_uri() . '/img',
		'ajax_url' => admin_url( 'admin-ajax.php' ),
		'query_vars' => json_encode( $wp_query->query ),
		'inc_slidebars' => ( $theme_opts['rhd_include_slidebars'] == '1' ) ? true : false,
		'inc_packery' => ( $theme_opts['rhd_include_packery'] == '1' ) ? true : false
	);
	wp_localize_script( 'child-main', 'wp_child_data', $data);
}


/**
 * Function: rhd_favicons
 *
 * Outputs default favicon linkage, generated by http://realfavicongenerator.net/
 **/
function rhd_favicons() {
	echo '
		<link rel="shortcut icon" href="' . RHD_THEME_DIR . '/favicon/favicon.ico">
		<link rel="apple-touch-icon" sizes="57x57" href="' . RHD_THEME_DIR . '/favicon/apple-touch-icon-57x57.png">
		<link rel="apple-touch-icon" sizes="114x114" href="' . RHD_THEME_DIR . '/favicon/apple-touch-icon-114x114.png">
		<link rel="apple-touch-icon" sizes="72x72" href="' . RHD_THEME_DIR . '/favicon/apple-touch-icon-72x72.png">
		<link rel="apple-touch-icon" sizes="144x144" href="' . RHD_THEME_DIR . '/favicon/apple-touch-icon-144x144.png">
		<link rel="apple-touch-icon" sizes="60x60" href="' . RHD_THEME_DIR . '/favicon/apple-touch-icon-60x60.png">
		<link rel="apple-touch-icon" sizes="120x120" href="' . RHD_THEME_DIR . '/favicon/apple-touch-icon-120x120.png">
		<link rel="apple-touch-icon" sizes="76x76" href="' . RHD_THEME_DIR . '/favicon/apple-touch-icon-76x76.png">
		<link rel="apple-touch-icon" sizes="152x152" href="' . RHD_THEME_DIR . '/favicon/apple-touch-icon-152x152.png">
		<link rel="icon" type="image/png" href="' . RHD_THEME_DIR . '/favicon/favicon-196x196.png" sizes="196x196">
		<link rel="icon" type="image/png" href="' . RHD_THEME_DIR . '/favicon/favicon-160x160.png" sizes="160x160">
		<link rel="icon" type="image/png" href="' . RHD_THEME_DIR . '/favicon/favicon-96x96.png" sizes="96x96">
		<link rel="icon" type="image/png" href="' . RHD_THEME_DIR . '/favicon/favicon-16x16.png" sizes="16x16">
		<link rel="icon" type="image/png" href="' . RHD_THEME_DIR . '/favicon/favicon-32x32.png" sizes="32x32">
		<meta name="msapplication-TileColor" content="#da532c">
		<meta name="msapplication-TileImage" content="' . RHD_THEME_DIR . '/favicon/mstile-144x144.png">
		<meta name="msapplication-config" content="' . RHD_THEME_DIR . '/favicon/browserconfig.xml">
	';
}
add_action( 'wp_head', 'rhd_favicons' );


/*
add_action( 'wp_enqueue_scripts', 'rhd_override_scripts' );
function rhd_override_scripts() {
	wp_dequeue_script( 'ajax-loop' );
	wp_enqueue_script( 'ajax-loop', RHD_CHILD_DIR . '/js/ajax-loop.js', array( 'jquery' ), null, true );

	// Localize template dirs
	global $wp_query;
	$data = array(
		'template_url' => get_stylesheet_directory_uri(),
		'parent_url' => get_template_directory_uri()
	);
	wp_localize_script( 'ajax-loop', 'wp_child_data', $data);
}
*/


/* ==========================================================================
	RHD MailChimp Widget
   ========================================================================== */

class RHD_Mailchimp_Widget_GH extends WP_Widget {
	public function __construct() {
		parent::__construct(
	 		'rhd_mailchimp_widget_gh', // Base ID
			'RHD MailChimp Subscribe Widget', // Name
			array( 'description' => __( 'Pre-configured MailChimp subscribe widget.', 'rhd' ), ) // Args
		);
	}

	public function update( $new_instance, $old_instance ) {
		// processes widget options to be saved
		return $new_instance;
	}

	public function widget( $args, $instance ) {
		extract( $args );

		wp_enqueue_script( 'rhd-mailchimp-js', RHD_CHILD_DIR . '/include/rhdwp-mc/rhd-mailchimp.js', array( 'jquery' ) );
		wp_enqueue_style( 'rhd-mailchimp-css', RHD_CHILD_DIR . '/include/rhdwp-mc/rhd-mailchimp.css' );

		$args['title'] = apply_filters( 'widget_title', $instance['title'] );
		$args['text'] = apply_filters( 'widget_text', empty( $instance['text'] ) ? '' : $instance['text'], $instance );
		$args['button'] = ( !empty( $instance['button'] ) ) ? $instance['button'] : "Submit";
		$args['fname'] = ( $instance['fname'] == 'yes' ) ? true : false;
		$args['lname'] = ( $instance['lname'] == 'yes' ) ? true : false;

		echo $before_widget;

		if ( $args['title'] )
			echo $before_title . $args['title'] . $after_title;

		$widget_id = substr( $this->id, -1, 1 );
		?>

		<div id="rhd_mc_widget-<?php echo $widget_id; ?>" class="rhd_mailchimp clearfix">

			<?php if ( !empty( $args['text'] ) ) : ?>
				<p class="rhd_mc_text"><?php echo $args['text']; ?></p>
			<?php endif; ?>

			<form id="rhd_mc_subscribe-<?php echo $widget_id; ?>" class="rhd_mc_subscribe clearfix" action="<?php echo RHD_CHILD_DIR; ?>/include/rhdwp-mc/lib/rhd-mc-subscribe.php" method="post">
				<?php if ( $args['fname'] ) : ?>
					<input id="rhd_mc_fname-<?php echo $widget_id; ?>" class="rhd_mc_fname" type="text" name="fname" placeholder="first">
				<?php endif; ?>

				<?php if ( $args['lname'] ) : ?>
					<input id="rhd_mc_lname-<?php echo $widget_id; ?>" class="rhd_mc_lname" type="text" name="lname" placeholder="last">
				<?php endif; ?>

				<input id="rhd_mc_email-<?php echo $widget_id; ?>" class="rhd_mc_email" type="email" name="email" placeholder="email">
				<input class="rhd_mc_form_id" type="hidden" value="<?php echo $widget_id; ?>">
				<input id="rhd_mc_submit-<?php echo $widget_id; ?>" class="rhd_mc_submit" type="submit" value="<?php echo $args['button']; ?>" name="submit-<?php echo $widget_id; ?>">
			</form>
			<div id="rhd_mc_thanks-<?php echo $widget_id; ?>" class="rhd_mc_thanks">
				<p>Subscribed!</p>
			</div><!-- #rhd_mc_thanks-<?php echo $widget_id; ?> -->
			<div id="rhd_mc_error-<?php echo $widget_id; ?>" class="rhd_mc_error">
				Please enter a valid email address.
			</div><!-- #rhd_mc_error-<?php echo $widget_id; ?> -->
		</div><!-- <?php echo $widget_id; ?> -->

	<?php echo $after_widget;

	}

	public function form( $instance ) {
		// outputs the options form on admin
		$args['title'] = esc_attr( $instance['title'] );
		$args['text'] = esc_textarea( $instance['text'] );
		$args['button'] = esc_attr( $instance['button'] );
		$args['fname'] = esc_attr( $instance['fname'] );
		$args['lname'] = esc_attr( $instance['lname'] );
		?>

		<h3>Widget Options:</h3>
		<p>
			<label for="<?php echo $this->get_field_id( 'title' ); ?>"><?php  _e( 'Widget Title (optional): ' ); ?></label>
			<input id="<?php echo $this->get_field_id('title'); ?>" name="<?php echo $this->get_field_name( 'title' ); ?>" type="text" value="<?php echo $args['title']; ?>" >
		</p>

		<p>
			<label for="<?php echo $this->get_field_id( 'text' ); ?>"><?php _e( 'Text to display (optional): ' ); ?></label>
			<textarea class="widefat" rows="3" cols="20" id="<?php echo $this->get_field_id( 'text' ); ?>" name="<?php echo $this->get_field_name( 'text' ); ?>"><?php echo $args['text']; ?></textarea>
		</p>

		<p>
			<label for="<?php echo $this->get_field_id( 'button'); ?>">Button text <em>(Default: Submit)</em>:</label>
			<input id="<?php echo $this->get_field_id('button'); ?>" name="<?php echo $this->get_field_name( 'button' ); ?>" type="text" value="<?php echo $args['button']; ?>" >
		</p>

		<h3>Optional Fields:</h3>
		<p>
			<input id="<?php echo $this->get_field_id( 'fname' ); ?>" name="<?php echo $this->get_field_name( 'fname' ); ?>" type="checkbox" value="yes" <?php if( $args['fname'] === 'yes' ){ echo 'checked="checked"'; } ?> />
			<label for="<?php echo $this->get_field_id( 'fname' ); ?>"><?php _e( 'First Name' ); ?></label>
		</p>
		<p>
			<input id="<?php echo $this->get_field_id( 'lname' ); ?>" name="<?php echo $this->get_field_name( 'lname' ); ?>" type="checkbox" value="yes" <?php if( $args['lname'] === 'yes' ){ echo 'checked="checked"'; } ?> />
			<label for="<?php echo $this->get_field_id( 'style_vertical' ); ?>"><?php _e( 'Last Name'); ?></label>
		</p>

	<?php
	}
}

function rhd_register_mailchimp_widget_gh() {
    register_widget( 'RHD_Mailchimp_Widget_GH' );
}
add_action( 'widgets_init', 'rhd_register_mailchimp_widget_gh' );
